<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Pages\imgs\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Ensayo.pdf" />
    <None Include="wwwroot\fotoprofesional.jpg" />
  </ItemGroup>

</Project>
